### ISSUE TITLE
July events

### ISSUE THREAD

**Issue by sethvincent** [openseattle/discuss#12]
Let's use this issue to plan out the events we're holding in July.

**Comment by sethvincent** [comment]
The only thing I know for sure so far: 

_July 2 at Socrata_
**The great migration: Code for Seattle -> Open Seattle**
We'll have a list of tasks for making the migration, and folks will be able to help.
If that doesn't take the whole time, it'll be usual civic hacking night after that.

**Comment by willscott** [comment]
TWIF has another event on 3rd thursdays, but we could use them another day of the month if desired.

**Comment by LukeSwart** [comment]
Any thoughts on hosting an all-day outdoor event? I'm here at the Electric Sky event, and the setup is great. I think we would need the following, at a minimum:

 * power supply
 * gazebo/tent for shade
 * extension cords and power strips
 * wifi hotspots
 * drinks

and as a bonus:

 * nearby swimming
 * food/drink (ie slushies)
 * invite people to bring hardware projects to build and demo outdoors

Some parks have a community center with power available, like Magnuson Park and Beacon Hill. Perhaps we can make a list of possible locations? Such an event might also work for NodeSchool.

**Comment by sethvincent** [comment]
:+1: on outdoor events.

seward park could be good, too.

**Comment by stina-seattle** [comment]
Seward Park has one outlet, at Shelter #3 (needs lengthy extension cord though). Shelter #3 has two amazing picnic tables, at the cost of $230/day. Wah.

**Comment by LukeSwart** [comment]
Here's the site for booking a hotspot via SPL: https://seattle.bibliocommons.com/item/show/3030520030_spl_hotspot

If we can't get one in time, I'm happy to use my phone/tablet as a hotspot as well.

**Comment by ptressel** [comment]
Here is the Seattle Parks picnic doc:
http://www.seattle.gov/parks/Reservations/docs/picnic_brochure.pdf
It says: "Electricity is not available at any of the picnic parks."  And: "IMPORTANT: Electricity is not provided."

If you want power, that's not a picnic site -- that's "facility rental".
http://www.seattle.gov/parks/facilities/rentals/
Waaaay down at the bottom of that page is a link to the fees.

Maybe we should do this:
http://spectrum.ieee.org/computing/it/it-takes-a-village
