### ISSUE TITLE
Socrata is Hiring!

### ISSUE THREAD

**Issue by chrismetcalf** [openseattle/discuss#20]
Please let me know if this isn't appropriate for this forum, but we're hiring for a number of different positions that might be interesting for Open Seattle folks:

- [Senior Web Dev](http://careers.socrata.com/jobs/?jvi=oibw1fwK,Job)
- [Front-End Software Engineer](http://careers.socrata.com/jobs/?jvi=obaCYfwF,Job)
- [Back-End Software Engineer](http://careers.socrata.com/jobs/?jvi=oP6aZfwO,Job)

I'm also hiring for a special role on the east coast, [Socrata Developer Evangelist](http://careers.socrata.com/jobs/?jvi=o4WPZfwy,Job), so if you know anybody out that way who might be a good partner for my team, I'd love to meet them!

If any of these look interesting to you, let me know. You can email me directly at chris.metcalf@socrata.com.

![](http://snuffleupadata.com/img/hello_world.png)

**Comment by sethvincent** [comment]
Cool!

Maybe we should have a page on the website, too, for promoting relevant positions. 

Something like openseattle.org/jobs

**Comment by chrismetcalf** [comment]
I like it! :+1:






On Tue, Aug 18, 2015 at 7:27 PM -0700, "Seth Vincent" <notifications@github.com> wrote:












Cool!



Maybe we should have a page on the website, too, for promoting relevant positions. 



Something like openseattle.org/jobs

**Comment by YonasBerhe** [comment]
Is Socrata hiring interns?

**Comment by sethvincent** [comment]
These specific positions are closed, so I'll close this issue. I'll also post the general jons link to our jobs channel in the slack. https://careers.socrata.com/jobs/
