### ISSUE TITLE
new stickers for january, 2016

### ISSUE THREAD

**Issue by sethvincent** [openseattle/discuss#28]
I'm about to order new stickers for 2016!

So far I plan to get stickers for these things:
- open seattle
- nwdata.org
- seattle.io
- popup arcade
- hey duwamish

**Comment by chrismetcalf** [comment]
Any interest in an Open Seattle snuffie? I could see if we could get that in our next round

**Comment by LukeSwart** [comment]
Yes, let's do Hey Duwamish stickers! I'm not sure on design though. The simplest example would probably just be our logo from our website - "Hey Duwamish!" using that Hey Arnold font. It'd be cool to design something new too (ie hexagon shape?), and maybe OpenSeattle can help :-D

**Comment by chrismetcalf** [comment]
FYI, I recently had stickers created by [Sticker Mule](https://www.stickermule.com/) and I was very very happy with the results. Highly recommended.

**Comment by sethvincent** [comment]
@chrismetcalf an open seattle snuffie would be super cute.

I updated the list and will put in an order in the next day or so. 

@LukeSwart lets get a hey duwamish sticker sorted out. I have an idea for a hexagon version that i could put together real quick.

**Comment by sethvincent** [comment]
we have stickers yay
![hex](https://cloud.githubusercontent.com/assets/164214/12225574/30929032-b7c2-11e5-9a71-5f67ec92812d.jpg)
