### ISSUE TITLE
2016 Seattle Open Data Day: Ship Camp

### ISSUE THREAD

**Issue by sethvincent** [openseattle/discuss#31]
## :ship: :tent: Ship Camp

Let's make Seattle Open Data Day the Ship Camp that @chrismetcalf suggested in https://github.com/openseattle/discuss/issues/25#issuecomment-161427836

Purpose of the event: Hey, we know you've got a project related to open data that isn't finished. Let's ship it.

I'm pretty sure we should use the :ship: ship and :tent: tent emoji in the design of the event site/materials.

**Comment by ptressel** [comment]
Good idea!  Is this in the same 3rd week of February time frame as last year?

**Comment by willscott** [comment]
what are the logistics of partially having the event on a ship? :ship:!
maybe taking a ferry across the sound or looking at an argosy thing?  It's
off-season, so possibly we could get a decent deal.

**Comment by ptressel** [comment]
@willscott  Much as I like ferry parties, I dunno as how we'd serve the actual purpose of shipping products. The duty cycle is low -- one gets maybe half an hour of time, punctuated by an hour or more of boarding, deboarding, waiting in line.  If there really is a desire to add in an actual ship, maybe make it an after party.  Also, not all of us have tethering via our phones in our phone plans, so would need wifi.  WSF wifi is via Boingo, and not free, IIRC.

**Comment by chrismetcalf** [comment]
@ptressel @willscott For the Evergreen Apps Contest, we actually had an event organized that was going to happen on the Bremerton ferry (until the ferry broke down). I bet if we got Will Saunders from the state involved, he could get us free wifi and ferry passes

**Comment by candacefaber** [comment]
Sorry for the late reply. CodeAcross/IODD is March 5 next year (according
to Hannah from CfA).

I'm with Pat - depends on the logistics/time on the water. It sounds
awesome if it works out. Alternative is we do ShipCamp followed by
ShipParty. :)

On Tue, Dec 22, 2015 at 12:22 PM, Chris Metcalf <notifications@github.com>
wrote:

> @ptressel <https://github.com/ptressel> @willscott
> <https://github.com/willscott> For the Evergreen Apps Contest, we
> actually had an event organized that was going to happen on the Bremerton
> ferry (until the ferry broke down). I bet if we got Will Saunders from the
> state involved, he could get us free wifi and ferry passes
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openseattle/discuss/issues/31#issuecomment-166721130>.
>



-- 

Candace Faber

Seattle, WA

twt: @candacefaber

candacefaber.com <http://www.candacefaber.com>

**Comment by JohnTigue** [comment]
Our [Seattle boundaries map repo](https://github.com/openseattle/seattle-boundaries) might be a candidate for this. Small sprint-sized tasks that render as maps are good for (literally) seeing results.

**Comment by licyeus** [comment]
Hi all, at a minimum, I'd be up for meeting at a café and shipping some code.

If we want to be more formal, we can try booking larger space / hosting a bigger event, but we're down to 4 weeks. I can help put together a website, but will need someone to handle booking the space. How many people did we get last year and with how much promotional lead-time?

And I agree with you, @JohnTigue, that's a good easy project and I've got some ideas for boundaries.seattle.io's UI that I should sit down and work on.

Anybody know other incomplete civic projects in need of some final touches?

**Comment by chrismetcalf** [comment]
Looks like this year it's on March 5th. I've been lapse on planning for this event as well: http://opendataday.org/

Are people still interested in setting something up. I can look into whether @socrata can host - we'll have just moved to our new digs in the International District!

**Comment by chrismetcalf** [comment]
I totally forgot that ODD this year conflicts with http://blacktothefuturehack.org/! Instead of organizing our own event, I suggest we reach out to the organizers of that event and see if they're open to marketing it as the Seattle option for ODD. I think the goals are very compatible and it'd work well.

**Comment by candacefaber** [comment]
​Good news _ one of your own has already been in touch! They need an open
data challenge, though, and we're trying to help them come up with a good
one. Ideas welcome.

I think it'll be great to combine forces and show that Open Seattle isn't
just an event organizing machine but a gathering place for civic hackers of
all stripes and a way to support/get the word out about everyone's events.

I can make a direct intro to organizer Tiffany Dockery if you want, or I
can swing this by her and we'll just host. Sorry, I could have sworn we'd
discussed this earlier!

Still love the idea of a shipcamp later this year (or just a big
unstructured open data hackathon) if y'all are up for it.

On Tue, Feb 16, 2016 at 1:46 PM, Chris Metcalf <notifications@github.com>
wrote:

> I totally forgot that ODD this year conflicts with
> http://blacktothefuturehack.org/! Instead of organizing our own event, I
> suggest we reach out to the organizers of that event and see if they're
> open to marketing it as the Seattle option for ODD. I think the goals are
> very compatible and it'd work well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openseattle/discuss/issues/31#issuecomment-184887447>.
>



-- 

Candace Faber

Seattle, WA

twt: @candacefaber

candacefaber.com <http://www.candacefaber.com>

**Comment by chrismetcalf** [comment]
Thanks @candacefaber! That's what I was looking for via text earlier today.
