### ISSUE TITLE
Event: January 19 Open Project Night

### ISSUE THREAD

**Issue by sethvincent** [openseattle/discuss#32]
## Location, date, time:
Socrata
January 19, 2016
6-9 p.m.

## Projects
- Hey Duwamish
- Seattle NodeSchool
- seattle.io
- _what else_

**Comment by chrismetcalf** [comment]
Yay!

![](http://snuffleupadata.com/img/data_helmet.png)

**Comment by Grand222** [comment]
May not be able to make it tonight. 
Reminder of my skills: I have experience in project selection, running portfolios containing up to 182 projects and the operations of a project office.
I created a quick project selection framework for one of the AmeriCorps groups
I have Non-Profit governance, public education events and non-profit fundraising experience.

**Comment by Grand222** [comment]
Want project ideas? 
https://www.codeforamerica.org/products/
They also have a projects tab
