### ISSUE TITLE
Moving monthly events to 2nd & 4th Wednesdays of the month

### ISSUE THREAD

**Issue by sethvincent** [openseattle/discuss#35]
It's confusing to have on event a month on Tuesdays and one a month on Thursdays.

After doing some research on other regular events it looks like 2nd and 4th Wednesdays works well.

Are there any substantial conflicts that would make these days not work?

Unless something really big comes up, which seems unlikely, let's move to 2nd and 4th Wednesdays in March.

**Comment by loganfranken** [comment]
I don't see any conflicts: the second Wednesday is technically the day of the Wallingford Art Walk (http://seattlepipeline.com/events/wallingford-art-walk/), but I'm not even sure if that still happens?

Either way, I don't see it as a major conflict.

**Comment by chrismetcalf** [comment]
Checking with our office manager but provisionally I approve.

**Comment by candacefaber** [comment]
Yes please! Pretty please! Thursdays are always such a busy night.

On Tue, Feb 16, 2016 at 9:48 PM, Chris Metcalf <notifications@github.com>
wrote:

> Checking with our office manager but provisionally I approve.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openseattle/discuss/issues/35#issuecomment-185038725>.
>



-- 

Candace Faber

Seattle, WA

twt: @candacefaber

candacefaber.com <http://www.candacefaber.com>

**Comment by sethvincent** [comment]
This is happening!
