### ISSUE TITLE
Event: March 9 at Socrata

### ISSUE THREAD

**Issue by sethvincent** [openseattle/discuss#36]
## Location, date, time:
Socrata
March 9, 2016
6-9 p.m.

## Talks
- Seattle Parks (description needed)
- Parks web app (description needed)

## Volunteers
- host: @candacefaber 

## Meetup announcement
http://www.meetup.com/openseattle/events/228962821/

**Comment by sethvincent** [comment]
I'll be out of town for this one! So we'll need someone to volunteer to be host.

@candacefaber will we have another guest from the city this month?

**Comment by candacefaber** [comment]
Yep! I can host. Seattle Parks wants in! They are looking to release new
data soon ahead of the AT&T Parks & Rec hackathon, so I should be a good
one. Change in tone from SPD. :)

**Comment by sethvincent** [comment]
Nice! In addition there's a good chance that we'll also have someone do a hands-on demo on how to visualize open data using React. I'll confirm next week.

Probably 30 minutes for each talk?

**Comment by candacefaber** [comment]
Yeah, let's touch base. I'm thinking that we can maybe do a quick
intro/icebreaker and then have people split off into groups after quick
pitches, rotating the space at an appropriate interval in case several
presenters need the projector.

I'll hop on Slack today so we can talk it over!

On Thu, Feb 18, 2016 at 6:45 PM, Seth Vincent <notifications@github.com>
wrote:

> Nice! In addition there's a good chance that we'll also have someone do a
> hands-on demo on how to visualize open data using React. I'll confirm next
> week.
>
> Probably 30 minutes for each talk?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openseattle/discuss/issues/36#issuecomment-186022073>.
>



-- 

Candace Faber

Seattle, WA

twt: @candacefaber

candacefaber.com <http://www.candacefaber.com>

**Comment by stedy** [comment]
Any availability to guest presentations? I have a Seattle parks webapp thats about 90% done, this would be a good motivator to get it done and then present it.

**Comment by sethvincent** [comment]
It turns out the "Visualizing open data with React" talk will move to the April 13 event.

@stedy That's great! Perfectly relevant to go with the other talk. I think you should plan on it.

**Comment by chrismetcalf** [comment]
@candacefaber Great news on the Parks & Rec data!

 ![Pizza](https://media3.giphy.com/media/I8PFuF7ZlARGM/200.gif)

This event will be the first one at our new address and in our new event space. Our new office will be at 705 5th Ave S (the big tall buildings in the plaza across the street to the west of Uwajimaya). We've got the big conference room on the first floor reserved, which should be big enough for our group. Just go in through the main entrance and we'll be right there on the right hand side.

**Comment by ptressel** [comment]
Uh oh...looks like 2nd Wednesday is going to be a permanent conflict with PuPPy (Puget Sound Programming Python, http://www.meetup.com/PSPPython/).  Don't want to have to miss OpenSeattle...
