### ISSUE TITLE
Event: April 13 at Socrata

### ISSUE THREAD

**Issue by sethvincent** [openseattle/discuss#37]
## Location, date, time:
Socrata
April 13, 2016
6-9 p.m.

## Talks
- Someone from the city (description needed)
- Visualizing open data with React, Per Nilsson, @coopy

## Volunteers
- host:

## Meetup announcement
http://www.meetup.com/openseattle/events/229941257/

**Comment by chrismetcalf** [comment]
77 registered! Unless there is objection, there will be 🍕

**Comment by sethvincent** [comment]
:+1:
