### ISSUE TITLE
Event: July 27 talks night at Socrata

### ISSUE THREAD

**Issue by sethvincent** [openseattle/discuss#47]
## Location, date, time:
Socrata
July 27, 2016
6-9 p.m.

## Talks
- A staff member from the Seattle City Clerk's office 
- Tim Thomas, UW Phd student, will talk about research around Seattle's neighborhoods, race, & micro-segregation.

## Meetup announcement
http://www.meetup.com/openseattle/events/232546905/

**Comment by chrismetcalf** [comment]
Oh no! I just realized this is also the same night Weird Al is playing at ZooTunes! Decisions Decisions!

![200](https://cloud.githubusercontent.com/assets/19971/15976405/5eb0cada-2f07-11e6-8285-87717934ca25.gif)

**Comment by sethvincent** [comment]
![](https://img.pandawhale.com/post-58568-weird-al-cool-gif-Imgur-Tumblr-xbYI.gif)

**Comment by ptressel** [comment]
Weird Al will also be at ZooTunes on the 26th, so all is not lost.

**Comment by chrismetcalf** [comment]
FYI, there's nothing up in http://www.meetup.com/openseattle/ for our next meeting! @sethvincent

**Comment by sethvincent** [comment]
i'll be sending out announcements on wednesday: http://www.meetup.com/openseattle/events/232546905
