### ISSUE TITLE
Event: Open Project Night on August 3

### ISSUE THREAD

**Issue by sethvincent** [openseattle/discuss#48]
## Location, date, time:
Youngstown Cultural Arts Center
August 3, 2016
6-9 p.m.

## Projects
- Seattle IO: https://github.com/seattleio/boundaries learn which boundaries are associated within a givien point to better understand how policies and services can affect you (https://boundaries.seattle.io/)
 **technologies used:**
  * Choo framework: https://github.com/yoshuawuyts/choo
  * node.js
  * turf.js
  * leaflet.js

- The Hey Duwamish! platform: https://github.com/smartercleanup/platform - a tool for community engagement within environmental cleanup projects (http://heyduwamish.org)
 **technologies used:**
  * Django framework
  * Docker
  * Serverless: http://serverless.com/
  * backbone.js
  * leaflet.js
  * PostGIS

- Or bring your own project!

**Comment by SoldierCoder** [comment]
It's August 2nd, can we hear something about the projects?

**Comment by LukeSwart** [comment]
@SoldierCoder I just updated the list of projects above - hope to see you there!

Let me know if you have further questions.
