### ISSUE TITLE
Invite people to openseattle.slack.com

### ISSUE THREAD

**Issue by sethvincent** [openseattle/discuss#8]

**Comment by sethvincent** [comment]
Invited will, candace, and chris so far.

**Comment by LukeSwart** [comment]
If it's ok, invite me too!

**Comment by sethvincent** [comment]
@LukeSwart Invited!

If anyone else wants an invite definitely leave a comment here.

**Comment by loganfranken** [comment]
@sethvincent I would love an invite as well! Thanks!

**Comment by sethvincent** [comment]
@loganfranken invited!

**Comment by candacefaber** [comment]
Hey! Which email did you send the invite to? It's not recognizing me. 



—

**Comment by gkbroderick** [comment]
Hey Seth! Thanks for DiscoTech. Definitely interested in being on the
openseattle slack channel!

**Comment by sethvincent** [comment]
@gkbroderick invited!

**Comment by sethvincent** [comment]
So this should allow people to join the open seattle slack without waiting for an invite: https://openseattleslack.herokuapp.com

someone should try it and see if it works!

**Comment by LukeSwart** [comment]
It's been working well! I posted this link on the #random channel if anyone needs access to it.

Therefore, I am closing this issue.

**Comment by larkin71** [comment]
Can someone invite me? jake@jetrail.co
